### ISSUE TITLE
Client fails when user is member of several organizations

### ISSUE THREAD

**Issue by eMxPi** [strongself/fabricio#44] opened 2017-12-26 16:44 UTC
Hi,

I've an account which belongs to 2 organizations. The app for the second organisation are never retrieved (always saying nil for object).

Is there any way to disconnect the client to reconnect with another account ?

**Comment by etolstoy** [comment] 2018-01-16 11:52
Thanks for reporting! The issue is duplicate of #45. There is already a PR that fixes this issue.

**Closed as completed by etolstoy** 2018-01-16 11:52 UTC
